export interface PetSeed {
  name: string;
  species: "dog" | "cat" | "bird" | "rabbit" | "reptile";
  breed: string;
  ageMonths: number;
  gender: "male" | "female";
  size: "small" | "medium" | "large";
  bio: string;
  traits: string[];
  city: string;
  state: string;
  photos: string[];
  adoptionFee: number;
}

export const petsSeedData: PetSeed[] = [
  {
    name: "Juniper",
    species: "dog",
    breed: "corgi mix",
    ageMonths: 18,
    gender: "female",
    size: "small",
    bio: "I operate like a tiny cruise director: breakfast at seven, neighborhood gossip at eight, heroic sploot by noon. If you own a tennis ball and a sense of humor, I already like you.",
    traits: ["apartment-friendly", "toy collector", "people-focused"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog7.jpg",
      "https://pets-images.dev-apis.com/pets/dog21.jpg",
      "https://pets-images.dev-apis.com/pets/dog3.jpg",
    ],
    adoptionFee: 325,
  },
  {
    name: "Tank",
    species: "dog",
    breed: "lab mix",
    ageMonths: 48,
    gender: "male",
    size: "large",
    bio: "My head is big, my heart is bigger, and I lean on people like I'm trying to merge into their lap. I take fetch very seriously but treat thunderstorms like a group cuddle opportunity.",
    traits: ["good with kids", "fetch fanatic", "couch potato"],
    city: "Bellevue",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog12.jpg",
      "https://pets-images.dev-apis.com/pets/dog4.jpg",
    ],
    adoptionFee: 180,
  },
  {
    name: "Ozzie",
    species: "dog",
    breed: "dachshund",
    ageMonths: 10,
    gender: "male",
    size: "small",
    bio: "I may be close to the ground, but I bring penthouse confidence to every room. Hide your socks unless you want me to curate a very exclusive dachshund collection.",
    traits: ["silly", "lap dog", "toy thief"],
    city: "Ballard",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog18.jpg",
      "https://pets-images.dev-apis.com/pets/dog5.jpg",
      "https://pets-images.dev-apis.com/pets/dog27.jpg",
    ],
    adoptionFee: 390,
  },
  {
    name: "Clementine",
    species: "dog",
    breed: "pit mix",
    ageMonths: 36,
    gender: "female",
    size: "medium",
    bio: "I wag with my whole torso and hand out kiss receipts for every pet I receive. Give me a squeaky toy and I'll perform my one-woman comedy special.",
    traits: ["goofy", "good with dogs", "kissing booth"],
    city: "Tacoma",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog9.jpg",
      "https://pets-images.dev-apis.com/pets/dog14.jpg",
    ],
    adoptionFee: 145,
  },
  {
    name: "Bruno",
    species: "dog",
    breed: "husky mix",
    ageMonths: 26,
    gender: "male",
    size: "large",
    bio: "I'm equal parts trail buddy and dramatic snow model, so yes, I will pose in a drift like it's my album cover. After adventures, I turn into a fuzzy space heater with opinions about bedtime.",
    traits: ["high energy", "needs a yard", "adventure buddy"],
    city: "Portland",
    state: "OR",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog23.jpg",
      "https://pets-images.dev-apis.com/pets/dog6.jpg",
      "https://pets-images.dev-apis.com/pets/dog31.jpg",
    ],
    adoptionFee: 220,
  },
  {
    name: "Poppy",
    species: "dog",
    breed: "chihuahua mix",
    ageMonths: 84,
    gender: "female",
    size: "small",
    bio: "I prefer soft blankets, warm laps, and a household that respects the ancient art of the afternoon nap. My tiny bark says security system; my tiny body says travel-size burrito.",
    traits: ["senior sweetheart", "lap dog", "apartment-friendly"],
    city: "Kirkland",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog2.jpg",
      "https://pets-images.dev-apis.com/pets/dog16.jpg",
    ],
    adoptionFee: 95,
  },
  {
    name: "Arlo",
    species: "dog",
    breed: "golden retriever",
    ageMonths: 14,
    gender: "male",
    size: "large",
    bio: "I'm a golden boy with a PhD in carrying sticks that are way too large for me. I greet every morning like it's the first day of summer camp.",
    traits: ["young dog", "good with dogs", "loves water"],
    city: "Denver",
    state: "CO",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog35.jpg",
      "https://pets-images.dev-apis.com/pets/dog11.jpg",
      "https://pets-images.dev-apis.com/pets/dog1.jpg",
    ],
    adoptionFee: 410,
  },
  {
    name: "Mabel",
    species: "dog",
    breed: "beagle mix",
    ageMonths: 62,
    gender: "female",
    size: "medium",
    bio: "I sing little beagle ballads when dinner is late, but otherwise I'm a pleasant roommate with excellent porch manners. Sniff walks are my love language.",
    traits: ["sniff walks", "vocal", "easygoing"],
    city: "Renton",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog8.jpg",
      "https://pets-images.dev-apis.com/pets/dog19.jpg",
      "https://pets-images.dev-apis.com/pets/dog24.jpg",
    ],
    adoptionFee: 135,
  },
  {
    name: "Fergus",
    species: "dog",
    breed: "terrier mix",
    ageMonths: 30,
    gender: "male",
    size: "small",
    bio: "I look like I was assembled from spare scruff and optimism. Toss me a squeaky hedgehog and watch me become a tiny, glorious tornado.",
    traits: ["scruffy", "playful", "good with older kids"],
    city: "Everett",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog13.jpg",
      "https://pets-images.dev-apis.com/pets/dog30.jpg",
    ],
    adoptionFee: 165,
  },
  {
    name: "Nori",
    species: "dog",
    breed: "shiba inu mix",
    ageMonths: 22,
    gender: "female",
    size: "medium",
    bio: "I'm stylish, self-possessed, and willing to be bribed with peanut butter for exactly one trick at a time. Once I trust you, I'll trail behind you like a very fox-like shadow.",
    traits: ["smart", "shy at first", "loves routine"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog20.jpg",
      "https://pets-images.dev-apis.com/pets/dog10.jpg",
      "https://pets-images.dev-apis.com/pets/dog36.jpg",
    ],
    adoptionFee: 275,
  },
  {
    name: "Diesel",
    species: "dog",
    breed: "boxer mix",
    ageMonths: 55,
    gender: "male",
    size: "large",
    bio: "I bounce when I'm happy, which is often, and my underbite deserves its own fan club. I'd love a home where toys are plentiful and couch snuggles are legally required.",
    traits: ["goofy", "strong boy", "crate trained"],
    city: "Kent",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog25.jpg",
      "https://pets-images.dev-apis.com/pets/dog15.jpg",
    ],
    adoptionFee: 160,
  },
  {
    name: "Sadie",
    species: "dog",
    breed: "australian shepherd",
    ageMonths: 20,
    gender: "female",
    size: "medium",
    bio: "I keep one eye on the horizon and one eye on you because managing the household is my passion project. Teach me something new and I'll act like valedictorian about it.",
    traits: ["very smart", "herding breed", "loves puzzle toys"],
    city: "Redmond",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog32.jpg",
      "https://pets-images.dev-apis.com/pets/dog17.jpg",
      "https://pets-images.dev-apis.com/pets/dog4.jpg",
    ],
    adoptionFee: 360,
  },
  {
    name: "Waffles",
    species: "dog",
    breed: "pug mix",
    ageMonths: 40,
    gender: "male",
    size: "small",
    bio: "I snort, I wiggle, and I nap in dramatic little croissant shapes. If you drop a crumb, I consider that a signed invitation.",
    traits: ["snorty", "cuddle bug", "food motivated"],
    city: "Redmond",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog6.jpg",
      "https://pets-images.dev-apis.com/pets/dog28.jpg",
    ],
    adoptionFee: 175,
  },
  {
    name: "Ivy",
    species: "dog",
    breed: "german shepherd mix",
    ageMonths: 28,
    gender: "female",
    size: "large",
    bio: "I have shepherd brains, movie-star ears, and a secret mushy side I only reveal after a few polite introductions. Once we're friends, I'll patrol the yard and then ask for forehead kisses.",
    traits: ["loyal", "shy at first", "not for cats"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog34.jpg",
      "https://pets-images.dev-apis.com/pets/dog12.jpg",
      "https://pets-images.dev-apis.com/pets/dog22.jpg",
    ],
    adoptionFee: 230,
  },
  {
    name: "Moose",
    species: "dog",
    breed: "bernese mountain dog mix",
    ageMonths: 72,
    gender: "male",
    size: "large",
    bio: "I am a very large gentleman who believes in slow walks, deep sighs, and lying directly in doorways. My ideal evening includes a chew bone and someone telling me I'm handsome in a low, respectful voice.",
    traits: ["senior sweetheart", "gentle giant", "low energy"],
    city: "Kirkland",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog29.jpg",
      "https://pets-images.dev-apis.com/pets/dog7.jpg",
    ],
    adoptionFee: 125,
  },
  {
    name: "Tilly",
    species: "dog",
    breed: "cattle dog mix",
    ageMonths: 16,
    gender: "female",
    size: "medium",
    bio: "I came preloaded with hustle, curiosity, and an impressive ability to notice where you hid the treats. Give me a job, even a fake one, and I'll glow with purpose.",
    traits: ["active", "trainable", "needs a job"],
    city: "Ballard",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog14.jpg",
      "https://pets-images.dev-apis.com/pets/dog33.jpg",
      "https://pets-images.dev-apis.com/pets/dog18.jpg",
    ],
    adoptionFee: 255,
  },
  {
    name: "Remy",
    species: "dog",
    breed: "poodle mix",
    ageMonths: 34,
    gender: "male",
    size: "medium",
    bio: "I have fancy curls and deeply unserious energy. I can go from neighborhood athlete to couch ornament in about four and a half minutes.",
    traits: ["smart", "low-shed coat", "velcro dog"],
    city: "Bellevue",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog11.jpg",
      "https://pets-images.dev-apis.com/pets/dog26.jpg",
    ],
    adoptionFee: 210,
  },
  {
    name: "Dot",
    species: "dog",
    breed: "jack russell terrier",
    ageMonths: 11,
    gender: "female",
    size: "small",
    bio: "I am powered by springs, sunshine, and the possibility that someone might throw the ball one more time. When the day is done, I curl into a tiny comma against your side.",
    traits: ["high energy", "ball obsessed", "small but mighty"],
    city: "Kirkland",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog37.jpg",
      "https://pets-images.dev-apis.com/pets/dog9.jpg",
      "https://pets-images.dev-apis.com/pets/dog2.jpg",
    ],
    adoptionFee: 320,
  },
  {
    name: "Banjo",
    species: "dog",
    breed: "coonhound mix",
    ageMonths: 44,
    gender: "male",
    size: "large",
    bio: "My ears arrive in the room before the rest of me, and I follow interesting smells like they're breaking news. I'm happiest when my nose is busy and my people are nearby.",
    traits: ["hound nose", "good on trails", "howler"],
    city: "Austin",
    state: "TX",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog5.jpg",
      "https://pets-images.dev-apis.com/pets/dog24.jpg",
      "https://pets-images.dev-apis.com/pets/dog38.jpg",
    ],
    adoptionFee: 140,
  },
  {
    name: "Lulu",
    species: "dog",
    breed: "bichon frise",
    ageMonths: 27,
    gender: "female",
    size: "small",
    bio: "I keep my white fluff in excellent condition and expect compliments to match. I adore being adored, but I'll return the favor by becoming your cheerful little shadow.",
    traits: ["grooming needs", "people-focused", "apartment-friendly"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog16.jpg",
      "https://pets-images.dev-apis.com/pets/dog1.jpg",
    ],
    adoptionFee: 260,
  },
  {
    name: "Kobe",
    species: "dog",
    breed: "rottweiler mix",
    ageMonths: 63,
    gender: "male",
    size: "large",
    bio: "I look tough in photos, then ruin the effect by leaning in for chin scratches. I take my neighborhood-watch duties seriously, but I clock out fast for snacks.",
    traits: ["protective look", "softie", "treat motivated"],
    city: "Kent",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog31.jpg",
      "https://pets-images.dev-apis.com/pets/dog13.jpg",
      "https://pets-images.dev-apis.com/pets/dog20.jpg",
    ],
    adoptionFee: 155,
  },
  {
    name: "Hazel",
    species: "dog",
    breed: "border collie mix",
    ageMonths: 24,
    gender: "female",
    size: "medium",
    bio: "I have bright eyes, quick feet, and a strong belief that frisbees are a respectable religion. If your life includes hikes, puzzle toys, or a backyard zoomie loop, I'm interested.",
    traits: ["frisbee fan", "high energy", "very smart"],
    city: "Redmond",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog10.jpg",
      "https://pets-images.dev-apis.com/pets/dog35.jpg",
    ],
    adoptionFee: 245,
  },
  {
    name: "Rufus",
    species: "dog",
    breed: "mastiff mix",
    ageMonths: 96,
    gender: "male",
    size: "large",
    bio: "I am old enough to know that racing is overrated and sun puddles are elite. Give me a soft bed and I'll repay you with opera-level snoring and loyal side-eye.",
    traits: ["senior dog", "lounger", "gentle giant"],
    city: "Tacoma",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog27.jpg",
      "https://pets-images.dev-apis.com/pets/dog8.jpg",
    ],
    adoptionFee: 85,
  },
  {
    name: "Millie",
    species: "dog",
    breed: "miniature schnauzer",
    ageMonths: 38,
    gender: "female",
    size: "small",
    bio: "I run on schnauzer curiosity and the assumption that every package delivery is specifically for me. My beard collects crumbs, wisdom, and occasionally evidence.",
    traits: ["alert", "toy lover", "grooming needs"],
    city: "Renton",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog22.jpg",
      "https://pets-images.dev-apis.com/pets/dog34.jpg",
      "https://pets-images.dev-apis.com/pets/dog6.jpg",
    ],
    adoptionFee: 215,
  },
  {
    name: "Theo",
    species: "dog",
    breed: "cattle dog mix",
    ageMonths: 8,
    gender: "male",
    size: "medium",
    bio: "I'm young, clever, and just mischievous enough to keep your shoes on speaking terms with the closet. Show me the routine and I'll throw my whole heart into it.",
    traits: ["puppy energy", "smart", "learning manners"],
    city: "Everett",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog3.jpg",
      "https://pets-images.dev-apis.com/pets/dog15.jpg",
      "https://pets-images.dev-apis.com/pets/dog39.jpg",
    ],
    adoptionFee: 285,
  },
  {
    name: "Suki",
    species: "dog",
    breed: "pomeranian mix",
    ageMonths: 15,
    gender: "female",
    size: "small",
    bio: "I float through the world like a glamorous dandelion puff with a surprisingly goofy sense of humor. I love being carried like a celebrity after a hard day of being cute.",
    traits: ["glamorous", "carried happily", "small dog"],
    city: "Sacramento",
    state: "CA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog24.jpg",
      "https://pets-images.dev-apis.com/pets/dog11.jpg",
    ],
    adoptionFee: 305,
  },
  {
    name: "Bear",
    species: "dog",
    breed: "shepherd-husky mix",
    ageMonths: 19,
    gender: "male",
    size: "large",
    bio: "I have one shepherd ear, one husky opinion, and enough enthusiasm to launch a small parade. I'd thrive with adventure outside and a proper flop on the floor afterward.",
    traits: ["adventure buddy", "needs exercise", "goofy"],
    city: "Kent",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog36.jpg",
      "https://pets-images.dev-apis.com/pets/dog19.jpg",
      "https://pets-images.dev-apis.com/pets/dog5.jpg",
    ],
    adoptionFee: 250,
  },
  {
    name: "Pearl",
    species: "dog",
    breed: "lab-pit mix",
    ageMonths: 50,
    gender: "female",
    size: "medium",
    bio: "I greet strangers with a full-body wag and friends with my patented happy snort. My specialty is making ordinary errands feel like a parade route.",
    traits: ["good with kids", "medium energy", "social butterfly"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog17.jpg",
      "https://pets-images.dev-apis.com/pets/dog32.jpg",
    ],
    adoptionFee: 150,
  },
  {
    name: "Gatsby",
    species: "dog",
    breed: "greyhound",
    ageMonths: 68,
    gender: "male",
    size: "large",
    bio: "I am tall, elegant, and built for dramatic window gazing. Don't let the runway legs fool you—I consider blankets a competitive sport.",
    traits: ["couch potato", "gentle", "long legs"],
    city: "Boise",
    state: "ID",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog21.jpg",
      "https://pets-images.dev-apis.com/pets/dog37.jpg",
      "https://pets-images.dev-apis.com/pets/dog14.jpg",
    ],
    adoptionFee: 135,
  },
  {
    name: "Rosie",
    species: "dog",
    breed: "cockapoo",
    ageMonths: 9,
    gender: "female",
    size: "small",
    bio: "I have baby curls, bright eyes, and the confidence of someone who has never paid a bill. I will chase a toy, miss it completely, and still expect applause.",
    traits: ["puppy energy", "cuddle bug", "good with dogs"],
    city: "Bellevue",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/dog39.jpg",
      "https://pets-images.dev-apis.com/pets/dog23.jpg",
      "https://pets-images.dev-apis.com/pets/dog9.jpg",
    ],
    adoptionFee: 345,
  },
  {
    name: "Marzipan",
    species: "cat",
    breed: "domestic shorthair",
    ageMonths: 30,
    gender: "female",
    size: "small",
    bio: "I believe in tidy paws, warm laundry, and supervising your keyboard with delicate authority. If you make room on the couch, I'll bring my best cinnamon-roll tuck.",
    traits: ["lap cat", "quiet home", "biscuit maker"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat5.jpg",
      "https://pets-images.dev-apis.com/pets/cat1.jpg",
      "https://pets-images.dev-apis.com/pets/cat9.jpg",
    ],
    adoptionFee: 120,
  },
  {
    name: "Leonard",
    species: "cat",
    breed: "orange tabby",
    ageMonths: 83,
    gender: "male",
    size: "medium",
    bio: "I'm a broad orange gentleman with a sweet face and exactly two speeds: hallway parade and deluxe nap. I chirp when I want attention, which is often and fair.",
    traits: ["chatty", "food motivated", "big boy"],
    city: "Ballard",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat12.jpg",
      "https://pets-images.dev-apis.com/pets/cat4.jpg",
    ],
    adoptionFee: 90,
  },
  {
    name: "Pixel",
    species: "cat",
    breed: "siamese mix",
    ageMonths: 14,
    gender: "male",
    size: "small",
    bio: "I like high shelves, dramatic stretches, and staring at birds like I'm storyboarding a heist. Once I pick my person, I like to drape across their shoulders like a very opinionated scarf.",
    traits: ["athletic", "bird watcher", "one-person cat"],
    city: "Kirkland",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat3.jpg",
      "https://pets-images.dev-apis.com/pets/cat10.jpg",
      "https://pets-images.dev-apis.com/pets/cat6.jpg",
    ],
    adoptionFee: 180,
  },
  {
    name: "Queenie",
    species: "cat",
    breed: "domestic longhair",
    ageMonths: 96,
    gender: "female",
    size: "medium",
    bio: "I have silky fur, polite manners, and the gaze of someone who has seen many things and chosen serenity. Brush me slowly and I'll reward you with a purr that sounds like distant thunder.",
    traits: ["senior cat", "brushing lover", "calm"],
    city: "Portland",
    state: "OR",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat14.jpg",
      "https://pets-images.dev-apis.com/pets/cat7.jpg",
    ],
    adoptionFee: 85,
  },
  {
    name: "Basil",
    species: "cat",
    breed: "tuxedo shorthair",
    ageMonths: 40,
    gender: "male",
    size: "small",
    bio: "I'm tuxedo formal from the whiskers down, but my hobbies are pure goblin. Open a cabinet and I'll appear as if summoned.",
    traits: ["curious", "cabinet inspector", "playful"],
    city: "Redmond",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat8.jpg",
      "https://pets-images.dev-apis.com/pets/cat2.jpg",
      "https://pets-images.dev-apis.com/pets/cat11.jpg",
    ],
    adoptionFee: 145,
  },
  {
    name: "Cricket",
    species: "cat",
    breed: "calico",
    ageMonths: 7,
    gender: "female",
    size: "small",
    bio: "I am a kitten-sized ricochet who believes curtain shadows are worthy opponents. After the acrobatics, I power down in your hoodie pocket.",
    traits: ["kitten energy", "acrobatic", "cuddle napper"],
    city: "Everett",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat1.jpg",
      "https://pets-images.dev-apis.com/pets/cat13.jpg",
    ],
    adoptionFee: 210,
  },
  {
    name: "Otto",
    species: "cat",
    breed: "domestic shorthair",
    ageMonths: 118,
    gender: "male",
    size: "medium",
    bio: "I've retired from nonsense and moved into a tasteful lifestyle of snacks, sunbeams, and being told I'm distinguished. I head-butt softly, as befits a gentleman of my years.",
    traits: ["senior cat", "gentle", "sunbeam expert"],
    city: "Sacramento",
    state: "CA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat9.jpg",
      "https://pets-images.dev-apis.com/pets/cat5.jpg",
    ],
    adoptionFee: 65,
  },
  {
    name: "Zelda",
    species: "cat",
    breed: "maine coon mix",
    ageMonths: 28,
    gender: "female",
    size: "medium",
    bio: "My fluff enters a room before the rest of me, and I know how to arrange myself for maximum admiration. I like conversation, brushing, and pretending I didn't just steal your chair.",
    traits: ["social", "fluffy", "brushing needed"],
    city: "Bellevue",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat6.jpg",
      "https://pets-images.dev-apis.com/pets/cat14.jpg",
      "https://pets-images.dev-apis.com/pets/cat3.jpg",
    ],
    adoptionFee: 195,
  },
  {
    name: "Mochi",
    species: "cat",
    breed: "domestic medium hair",
    ageMonths: 18,
    gender: "male",
    size: "small",
    bio: "I am soft in every possible direction and prone to melting into loaf form beside your laptop. Toss me a crinkle toy and I'll surprise you with Olympic footwork.",
    traits: ["soft loaf", "playful", "easygoing"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat11.jpg",
      "https://pets-images.dev-apis.com/pets/cat8.jpg",
    ],
    adoptionFee: 165,
  },
  {
    name: "Faye",
    species: "cat",
    breed: "tabby",
    ageMonths: 54,
    gender: "female",
    size: "small",
    bio: "I keep my affection on a slow simmer, then suddenly I'm asleep against your knee like we've known each other for years. Quiet homes bring out my funniest little squeaks.",
    traits: ["shy at first", "sweet", "quiet home"],
    city: "Tacoma",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat2.jpg",
      "https://pets-images.dev-apis.com/pets/cat12.jpg",
      "https://pets-images.dev-apis.com/pets/cat4.jpg",
    ],
    adoptionFee: 110,
  },
  {
    name: "Solomon",
    species: "cat",
    breed: "bombay mix",
    ageMonths: 33,
    gender: "male",
    size: "small",
    bio: "I have sleek black fur and the habit of appearing silently at your elbow like a tiny butler. I enjoy routines, respectful compliments, and drinking water as dramatically as possible.",
    traits: ["sleek", "routine lover", "independent"],
    city: "Renton",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat7.jpg",
      "https://pets-images.dev-apis.com/pets/cat10.jpg",
    ],
    adoptionFee: 145,
  },
  {
    name: "Pippa",
    species: "cat",
    breed: "dilute tortoiseshell",
    ageMonths: 12,
    gender: "female",
    size: "small",
    bio: "I am small, peachy, and entirely convinced your shoelaces exist for my enrichment. When I'm done causing kitten headlines, I purr myself to sleep in your lap.",
    traits: ["kitten", "shoelace hunter", "lap purrer"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat13.jpg",
      "https://pets-images.dev-apis.com/pets/cat1.jpg",
      "https://pets-images.dev-apis.com/pets/cat6.jpg",
    ],
    adoptionFee: 175,
  },
  {
    name: "Harvey",
    species: "cat",
    breed: "domestic longhair",
    ageMonths: 72,
    gender: "male",
    size: "medium",
    bio: "I wear a magnificent floof coat and act like a retired poet with very specific snack preferences. If you read on the couch, I'll be the warm bookmark.",
    traits: ["fluffy", "couch companion", "snacky"],
    city: "Denver",
    state: "CO",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat4.jpg",
      "https://pets-images.dev-apis.com/pets/cat9.jpg",
    ],
    adoptionFee: 95,
  },
  {
    name: "Nell",
    species: "cat",
    breed: "snowshoe mix",
    ageMonths: 22,
    gender: "female",
    size: "small",
    bio: "I have blue-eyed curiosity and a soft little meow that sounds like I'm asking permission to be adorable. New places make me cautious, but wand toys turn me brave.",
    traits: ["shy at first", "wand toy fan", "blue-eyed"],
    city: "Kent",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/cat10.jpg",
      "https://pets-images.dev-apis.com/pets/cat3.jpg",
      "https://pets-images.dev-apis.com/pets/cat12.jpg",
    ],
    adoptionFee: 160,
  },
  {
    name: "Peaches",
    species: "bird",
    breed: "cockatiel",
    ageMonths: 18,
    gender: "female",
    size: "small",
    bio: "I whistle along with the microwave and consider myself part of the kitchen staff. Offer me a finger perch and I'll deliver a cheerful little head bob.",
    traits: ["whistler", "hand-tame", "friendly"],
    city: "Ballard",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird4.jpg",
      "https://pets-images.dev-apis.com/pets/bird1.jpg",
    ],
    adoptionFee: 95,
  },
  {
    name: "Disco",
    species: "bird",
    breed: "budgerigar",
    ageMonths: 9,
    gender: "male",
    size: "small",
    bio: "I'm a pocket-sized party with feathers, opinions, and a heroic amount of mirror confidence. Put on music and I'll start my tiny club residency.",
    traits: ["chatty", "mirror lover", "beginner-friendly"],
    city: "Redmond",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird8.jpg",
      "https://pets-images.dev-apis.com/pets/bird2.jpg",
    ],
    adoptionFee: 65,
  },
  {
    name: "Olive",
    species: "bird",
    breed: "green-cheek conure",
    ageMonths: 30,
    gender: "female",
    size: "small",
    bio: "I am clever, nosy, and extremely interested in whatever snack you hoped to keep to yourself. Give me safe toys to shred and I'll stay busy like a feathered contractor.",
    traits: ["smart", "toy shredder", "food curious"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird3.jpg",
      "https://pets-images.dev-apis.com/pets/bird7.jpg",
      "https://pets-images.dev-apis.com/pets/bird5.jpg",
    ],
    adoptionFee: 145,
  },
  {
    name: "Senator",
    species: "bird",
    breed: "african grey",
    ageMonths: 84,
    gender: "male",
    size: "medium",
    bio: "I speak fluent side-eye and enjoy narrating household business from a dignified perch. Earn my trust and I'll show off my sweet side under all this statesman energy.",
    traits: ["talker", "observant", "experienced home preferred"],
    city: "Portland",
    state: "OR",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird9.jpg",
      "https://pets-images.dev-apis.com/pets/bird4.jpg",
    ],
    adoptionFee: 150,
  },
  {
    name: "Saffron",
    species: "bird",
    breed: "lovebird",
    ageMonths: 14,
    gender: "female",
    size: "small",
    bio: "I am bright, busy, and in favor of dramatic swings and paper strips. My heart is small but mighty, and I love a routine I can chirp about.",
    traits: ["active", "busy beak", "routine lover"],
    city: "Bellevue",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird2.jpg",
      "https://pets-images.dev-apis.com/pets/bird6.jpg",
    ],
    adoptionFee: 75,
  },
  {
    name: "Figaro",
    species: "bird",
    breed: "canary",
    ageMonths: 20,
    gender: "male",
    size: "small",
    bio: "I don't need much—just a sunny window, a tidy seed dish, and an audience for my greatest hits. I sing like I know rent is due and morale depends on me.",
    traits: ["singer", "low-maintenance", "window watcher"],
    city: "Tacoma",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird5.jpg",
      "https://pets-images.dev-apis.com/pets/bird1.jpg",
    ],
    adoptionFee: 55,
  },
  {
    name: "Joanie",
    species: "bird",
    breed: "parakeet",
    ageMonths: 11,
    gender: "female",
    size: "small",
    bio: "I flit first and think later, which keeps life breezy. Once I settle in, I like chatting softly to myself like I'm hosting a tiny podcast.",
    traits: ["tiny chatterbox", "active", "beginner-friendly"],
    city: "Everett",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird7.jpg",
      "https://pets-images.dev-apis.com/pets/bird3.jpg",
    ],
    adoptionFee: 60,
  },
  {
    name: "Racket",
    species: "bird",
    breed: "cockatiel",
    ageMonths: 48,
    gender: "male",
    size: "small",
    bio: "I wolf-whistle at suspiciously handsome lamps and climb my cage like it's a jungle gym. Bedtime scratches turn my rowdy act into instant marshmallow.",
    traits: ["whistler", "head-scratch fan", "playful"],
    city: "Kirkland",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird1.jpg",
      "https://pets-images.dev-apis.com/pets/bird8.jpg",
      "https://pets-images.dev-apis.com/pets/bird9.jpg",
    ],
    adoptionFee: 85,
  },
  {
    name: "Tiki",
    species: "bird",
    breed: "caique",
    ageMonths: 36,
    gender: "female",
    size: "medium",
    bio: "I bring carnival energy in a compact package and have strong feelings about the correct placement of every toy. Teach me a game and I'll commit like it's my full-time job.",
    traits: ["clownish", "smart", "needs enrichment"],
    city: "Austin",
    state: "TX",
    photos: [
      "https://pets-images.dev-apis.com/pets/bird6.jpg",
      "https://pets-images.dev-apis.com/pets/bird2.jpg",
      "https://pets-images.dev-apis.com/pets/bird4.jpg",
    ],
    adoptionFee: 135,
  },
  {
    name: "Butterbean",
    species: "rabbit",
    breed: "holland lop",
    ageMonths: 13,
    gender: "female",
    size: "small",
    bio: "I am round in spirit, soft in fur, and surprisingly quick when lettuce enters the chat. My favorite move is a joyful binky followed by an innocent face.",
    traits: ["binky champion", "litter trained", "sweet"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/rabbit2.jpg",
      "https://pets-images.dev-apis.com/pets/rabbit1.jpg",
    ],
    adoptionFee: 110,
  },
  {
    name: "Thistle",
    species: "rabbit",
    breed: "mini rex",
    ageMonths: 29,
    gender: "male",
    size: "small",
    bio: "I like tidy hay piles, gentle pets, and rearranging my blankets with interior-designer focus. If you're patient, I'll hop over to inspect your shoelaces personally.",
    traits: ["gentle", "blanket arranger", "shy at first"],
    city: "Renton",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/rabbit3.jpg",
      "https://pets-images.dev-apis.com/pets/rabbit2.jpg",
    ],
    adoptionFee: 95,
  },
  {
    name: "Opal",
    species: "rabbit",
    breed: "netherland dwarf",
    ageMonths: 8,
    gender: "female",
    size: "small",
    bio: "I may be tiny, but I possess CEO confidence and very fast feet. Give me tunnels and I become a blur with whiskers.",
    traits: ["tiny tornado", "curious", "tunnel lover"],
    city: "Bellevue",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/rabbit1.jpg",
      "https://pets-images.dev-apis.com/pets/rabbit3.jpg",
    ],
    adoptionFee: 125,
  },
  {
    name: "Cardamom",
    species: "rabbit",
    breed: "lionhead mix",
    ageMonths: 52,
    gender: "male",
    size: "small",
    bio: "I'm a fluffy little librarian who prefers calm voices and consistent snack service. Once I feel safe, I do the cutest sideways zoom you've ever seen.",
    traits: ["calm", "soft-coated", "quiet home"],
    city: "Ballard",
    state: "WA",
    photos: ["https://pets-images.dev-apis.com/pets/rabbit2.jpg"],
    adoptionFee: 80,
  },
  {
    name: "Gnocchi",
    species: "reptile",
    breed: "bearded dragon",
    ageMonths: 22,
    gender: "male",
    size: "medium",
    bio: "I enjoy basking like a tiny desert king and judging salads by presentation. Carry me around for a bit and I'll pose on your shoulder like I pay rent.",
    traits: ["great with beginners", "basking enthusiast", "calm"],
    city: "Seattle",
    state: "WA",
    photos: [
      "https://pets-images.dev-apis.com/pets/reptile1.jpg",
      "https://pets-images.dev-apis.com/pets/reptile2.jpg",
    ],
    adoptionFee: 95,
  },
  {
    name: "Vanta",
    species: "reptile",
    breed: "leopard gecko",
    ageMonths: 38,
    gender: "female",
    size: "small",
    bio: "I'm low-key, velvet-spotted, and happiest when my warm hide is just right. I don't do drama, but I will stalk a cricket with blockbuster intensity.",
    traits: ["low-maintenance", "nocturnal", "insect hunter"],
    city: "Redmond",
    state: "WA",
    photos: ["https://pets-images.dev-apis.com/pets/reptile2.jpg"],
    adoptionFee: 75,
  },
  {
    name: "Marmalade",
    species: "reptile",
    breed: "corn snake",
    ageMonths: 60,
    gender: "male",
    size: "medium",
    bio: "I move through life one elegant slither at a time and appreciate a calm, steady roommate. Let me explore safely and I'll reward you by being the coolest conversation starter in the apartment.",
    traits: ["gentle", "curious", "calm handling"],
    city: "Boise",
    state: "ID",
    photos: ["https://pets-images.dev-apis.com/pets/reptile1.jpg"],
    adoptionFee: 65,
  },
];
